terraform {
  required_version = ">= 1.3.0"

  required_providers {
    local = {
      source  = "hashicorp/local"
      version = "~> 2.5"
    }
  }
}

locals {
  out = trimsuffix(var.output_dir, "/")

  # Build location blocks for Nginx config
  nginx_locations = join("\n\n", [
    for loc in var.locations :
    <<-BLOCK
      location ${loc.path} {
          proxy_pass         http://${loc.backend_host}:${loc.backend_port};
          proxy_set_header   Host $host;
          proxy_set_header   X-Real-IP $remote_addr;
          proxy_read_timeout ${loc.timeout};
      }
    BLOCK
  ])

  # HAProxy backend servers
  haproxy_servers = join("\n", [
    for idx, srv in var.haproxy_servers :
    "    server ${srv.name} ${srv.host}:${srv.port} check weight ${srv.weight}"
  ])
}

# ------------------------------------------------------------------
# Nginx virtual host config
# ------------------------------------------------------------------
resource "local_file" "nginx_conf" {
  filename        = "${local.out}/nginx.conf"
  file_permission = "0644"
  content         = <<-NGINX
    # Nginx virtual host — generated by Terraform
    # Server: ${var.server_name}

    upstream backend_pool {
        ${join("\n    ", [for s in var.haproxy_servers : "server ${s.host}:${s.port};"])}
    }

    server {
        listen      80;
        listen      [::]:80;
        server_name ${var.server_name};

        access_log  /var/log/nginx/${var.server_name}.access.log;
        error_log   /var/log/nginx/${var.server_name}.error.log warn;

        ${local.nginx_locations}

        location /health {
            return 200 'OK';
            add_header Content-Type text/plain;
        }
    }
  NGINX
}

# ------------------------------------------------------------------
# HAProxy backend config
# ------------------------------------------------------------------
resource "local_file" "haproxy_conf" {
  filename        = "${local.out}/haproxy.cfg"
  file_permission = "0644"
  content         = <<-HAPROXY
    # HAProxy configuration — generated by Terraform

    global
        log stdout format raw local0
        maxconn 10000

    defaults
        log global
        mode http
        option httplog
        timeout connect 5s
        timeout client  30s
        timeout server  30s

    frontend http_front
        bind *:80
        default_backend ${var.server_name}_backend

    backend ${var.server_name}_backend
        balance roundrobin
        option httpchk GET /health
    ${local.haproxy_servers}
  HAPROXY
}
