terraform {
  required_version = ">= 1.3.0"

  required_providers {
    random = {
      source  = "hashicorp/random"
      version = "~> 3.6"
    }
    local = {
      source  = "hashicorp/local"
      version = "~> 2.5"
    }
  }
}

locals {
  out = trimsuffix(var.output_dir, "/")
}

# ------------------------------------------------------------------
# Secrets
# ------------------------------------------------------------------
resource "random_password" "secret_key" {
  length  = 50
  special = false # Django SECRET_KEY avoids some special chars
}

resource "random_password" "jwt_secret" {
  length           = 64
  special          = true
  override_special = "+-_="
}

resource "random_string" "app_id" {
  length  = 12
  upper   = false
  special = false
}

resource "random_integer" "http_port" {
  min = 8000
  max = 8999
}

# ------------------------------------------------------------------
# YAML config file
# ------------------------------------------------------------------
resource "local_file" "app_config" {
  filename        = "${local.out}/config.yaml"
  file_permission = "0640"
  content         = <<-YAML
    # Application configuration — generated by Terraform
    # WARNING: This file contains sensitive values. Do NOT commit it.

    app:
      id: "${random_string.app_id.result}"
      name: "${var.app_name}"
      env: "${var.app_env}"
      debug: ${var.app_env == "development" ? "true" : "false"}
      port: ${random_integer.http_port.result}

    security:
      secret_key: "${random_password.secret_key.result}"
      jwt_secret: "${random_password.jwt_secret.result}"
      jwt_algorithm: "HS256"
      token_expiry_hours: 24
      allowed_hosts:
        - "localhost"
        - "127.0.0.1"

    database:
      host: "localhost"
      port: 5432
      name: "${var.app_name}_${var.app_env}"
      pool_size: 5
      timeout: 30

    logging:
      level: ${var.app_env == "production" ? "WARNING" : "DEBUG"}
      format: "%(asctime)s %(levelname)s %(name)s %(message)s"
  YAML
}

# ------------------------------------------------------------------
# .env secrets file
# ------------------------------------------------------------------
resource "local_sensitive_file" "secrets_env" {
  filename        = "${local.out}/.env.secrets"
  file_permission = "0600"
  content         = <<-ENV
    # Secrets generated by Terraform — keep this file private
    SECRET_KEY=${random_password.secret_key.result}
    JWT_SECRET=${random_password.jwt_secret.result}
    APP_ID=${random_string.app_id.result}
    HTTP_PORT=${random_integer.http_port.result}
  ENV
}
