terraform {
  required_version = ">= 1.3.0"

  required_providers {
    local = {
      source  = "hashicorp/local"
      version = "~> 2.5"
    }
  }
}

locals {
  out = trimsuffix(var.output_dir, "/")

  # Environment-specific overrides merged on top of defaults
  defaults = {
    debug        = "false"
    log_level    = "WARNING"
    replicas     = "1"
    cache_ttl    = "3600"
    rate_limit   = "1000"
  }

  env_overrides = {
    development = {
      debug      = "true"
      log_level  = "DEBUG"
      replicas   = "1"
      rate_limit = "9999"
    }
    staging = {
      log_level  = "INFO"
      replicas   = "2"
      rate_limit = "500"
    }
    production = {
      replicas   = "3"
      cache_ttl  = "86400"
      rate_limit = "200"
    }
  }

  # Final merged config per environment
  env_configs = {
    for env in var.environments :
    env => merge(local.defaults, lookup(local.env_overrides, env, {}))
  }
}

# ------------------------------------------------------------------
# One .env file per environment
# ------------------------------------------------------------------
resource "local_file" "env" {
  for_each = local.env_configs

  filename        = "${local.out}/.env.${each.key}"
  file_permission = "0644"
  content         = <<-EOF
    # Environment: ${upper(each.key)}
    # Generated by Terraform

    APP_NAME=${var.app_name}
    APP_ENV=${each.key}
    APP_DEBUG=${each.value.debug}

    LOG_LEVEL=${each.value.log_level}
    REPLICAS=${each.value.replicas}
    CACHE_TTL_SECONDS=${each.value.cache_ttl}
    RATE_LIMIT_RPM=${each.value.rate_limit}

    DB_HOST=db.${each.key}.internal
    DB_PORT=5432
    DB_NAME=${var.app_name}_${each.key}

    REDIS_URL=redis://redis.${each.key}.internal:6379/0
  EOF
}

# ------------------------------------------------------------------
# Summary file
# ------------------------------------------------------------------
resource "local_file" "summary" {
  filename        = "${local.out}/SUMMARY.txt"
  file_permission = "0644"
  content = join("\n", concat(
    ["Multi-environment config summary", "================================", ""],
    [for env, f in local_file.env : "  ${env}  =>  ${f.filename}"],
    [""]
  ))
}
