terraform {
  required_version = ">= 1.3.0"

  required_providers {
    random = {
      source  = "hashicorp/random"
      version = "~> 3.6"
    }
    local = {
      source  = "hashicorp/local"
      version = "~> 2.5"
    }
  }
}

locals {
  out = trimsuffix(var.output_dir, "/")
}

# ------------------------------------------------------------------
# One random token per entry
# ------------------------------------------------------------------
resource "random_password" "tokens" {
  for_each = toset(var.token_names)

  length           = var.token_length
  special          = false # URL-safe alphanumeric tokens
  upper            = true
  lower            = true
  numeric          = true
}

# ------------------------------------------------------------------
# Write each token to its own file (sensitive, 0600)
# ------------------------------------------------------------------
resource "local_sensitive_file" "token_files" {
  for_each = random_password.tokens

  filename        = "${local.out}/${each.key}.token"
  file_permission = "0600"
  content         = each.value.result
}

# ------------------------------------------------------------------
# Index file listing all token paths (non-sensitive, 0644)
# ------------------------------------------------------------------
resource "local_file" "token_index" {
  filename        = "${local.out}/INDEX"
  file_permission = "0644"
  content = join("\n", concat(
    ["# Token file index — generated by Terraform", ""],
    [for name in sort(var.token_names) : "${name}  =>  ${local.out}/${name}.token"],
    [""]
  ))
}
