output "files_created" {
  description = "List of all files generated by the project scaffold."
  value = [
    local_file.readme.filename,
    local_file.gitignore.filename,
    local_file.makefile.filename,
    local_file.config.filename,
  ]
}

output "project_dir" {
  description = "Root directory of the scaffolded project."
  value       = local.dir
}
