terraform {
  required_version = ">= 1.3.0"

  required_providers {
    local = {
      source  = "hashicorp/local"
      version = "~> 2.5"
    }
  }
}

locals {
  out = trimsuffix(var.output_dir, "/")
}

# ------------------------------------------------------------------
# README
# ------------------------------------------------------------------
resource "local_file" "readme" {
  filename        = "${local.out}/README.md"
  file_permission = "0644"
  content         = <<-EOF
    # ${var.project_name}

    > Generated by Terraform on ${timestamp()}

    ## Description
    ${var.project_description}

    ## Getting Started
    ```bash
    make install
    make run
    ```
  EOF
}

# ------------------------------------------------------------------
# .gitignore
# ------------------------------------------------------------------
resource "local_file" "gitignore" {
  filename        = "${local.out}/.gitignore"
  file_permission = "0644"
  content         = <<-EOF
    # Terraform
    .terraform/
    .terraform.lock.hcl
    terraform.tfstate
    terraform.tfstate.backup
    *.tfplan
    override.tf
    override.tf.json
    *_override.tf
    *_override.tf.json

    # Environment files
    .env
    .env.local
    .env.*.local

    # OS
    .DS_Store
    Thumbs.db

    # Editor
    .idea/
    .vscode/
    *.swp
    *.swo
  EOF
}

# ------------------------------------------------------------------
# .env.example
# ------------------------------------------------------------------
resource "local_file" "env_example" {
  filename        = "${local.out}/.env.example"
  file_permission = "0644"
  content         = <<-EOF
    # Application settings — copy to .env and fill in real values
    APP_NAME=${var.project_name}
    APP_ENV=development
    APP_PORT=8080
    APP_DEBUG=true

    # Database
    DB_HOST=localhost
    DB_PORT=5432
    DB_NAME=mydb
    DB_USER=myuser
    DB_PASS=changeme

    # Secrets (never commit real values)
    SECRET_KEY=replace_with_a_random_secret
    JWT_SECRET=replace_with_a_random_secret
  EOF
}

# ------------------------------------------------------------------
# Makefile
# ------------------------------------------------------------------
resource "local_file" "makefile" {
  filename        = "${local.out}/Makefile"
  file_permission = "0644"
  content         = <<-EOF
    .PHONY: all install run test lint clean

    all: install

    install:
    	@echo "Installing dependencies for ${var.project_name}…"

    run:
    	@echo "Starting ${var.project_name}…"

    test:
    	@echo "Running tests…"

    lint:
    	@echo "Running linter…"

    clean:
    	@echo "Cleaning build artefacts…"
  EOF
}
