terraform {
  required_version = ">= 1.3.0"

  required_providers {
    random = {
      source  = "hashicorp/random"
      version = "~> 3.6"
    }
    local = {
      source  = "hashicorp/local"
      version = "~> 2.5"
    }
    null = {
      source  = "hashicorp/null"
      version = "~> 3.2"
    }
  }
}

locals {
  out = trimsuffix(var.output_dir, "/")

  services = {
    api      = { image = "python:3.12-slim",    internal_port = 8000, description = "FastAPI backend" }
    worker   = { image = "python:3.12-slim",    internal_port = 8001, description = "Background job processor" }
    frontend = { image = "node:20-alpine",       internal_port = 3000, description = "React SPA dev server" }
  }
}

# ------------------------------------------------------------------
# Random ports (avoids port collisions on the developer machine)
# ------------------------------------------------------------------
resource "random_integer" "api_port" {
  min = 8100; max = 8199
}

resource "random_integer" "worker_port" {
  min = 8200; max = 8299
}

resource "random_integer" "frontend_port" {
  min = 3100; max = 3199
}

locals {
  port_map = {
    api      = random_integer.api_port.result
    worker   = random_integer.worker_port.result
    frontend = random_integer.frontend_port.result
  }
}

# ------------------------------------------------------------------
# Shared secrets
# ------------------------------------------------------------------
resource "random_password" "secret_key" {
  length  = 50
  special = false
}

resource "random_password" "db_password" {
  length           = 24
  special          = true
  override_special = "!#$%&*"
}

resource "random_string" "correlation_seed" {
  length  = 16
  upper   = false
  special = false
}

# ------------------------------------------------------------------
# Per-service .env files
# ------------------------------------------------------------------
resource "local_file" "service_env" {
  for_each = local.services

  filename        = "${local.out}/services/${each.key}/.env"
  file_permission = "0640"
  content         = <<-ENV
    # ${each.value.description}
    SERVICE_NAME=${each.key}
    SERVICE_PORT=${local.port_map[each.key]}

    # Shared secrets
    SECRET_KEY=${random_password.secret_key.result}
    DB_HOST=db
    DB_PORT=5432
    DB_NAME=${var.project_name}
    DB_PASS=${random_password.db_password.result}

    # Tracing
    CORRELATION_SEED=${random_string.correlation_seed.result}
  ENV
}

# ------------------------------------------------------------------
# Master .env (used by Docker Compose)
# ------------------------------------------------------------------
resource "local_sensitive_file" "master_env" {
  filename        = "${local.out}/.env.master"
  file_permission = "0600"
  content         = <<-ENV
    PROJECT=${var.project_name}

    API_PORT=${random_integer.api_port.result}
    WORKER_PORT=${random_integer.worker_port.result}
    FRONTEND_PORT=${random_integer.frontend_port.result}

    DB_PASSWORD=${random_password.db_password.result}
    SECRET_KEY=${random_password.secret_key.result}
  ENV
}

# ------------------------------------------------------------------
# Docker Compose file
# ------------------------------------------------------------------
resource "local_file" "docker_compose" {
  filename        = "${local.out}/docker-compose.yml"
  file_permission = "0644"
  content         = <<-YAML
    # Docker Compose — generated by Terraform
    # Project: ${var.project_name}

    version: "3.9"

    services:
      api:
        image: ${local.services.api.image}
        env_file: ./services/api/.env
        ports:
          - "${random_integer.api_port.result}:${local.services.api.internal_port}"
        depends_on:
          - db

      worker:
        image: ${local.services.worker.image}
        env_file: ./services/worker/.env
        depends_on:
          - db

      frontend:
        image: ${local.services.frontend.image}
        env_file: ./services/frontend/.env
        ports:
          - "${random_integer.frontend_port.result}:${local.services.frontend.internal_port}"

      db:
        image: postgres:16-alpine
        environment:
          POSTGRES_DB: ${var.project_name}
          POSTGRES_PASSWORD: ${random_password.db_password.result}
        volumes:
          - db_data:/var/lib/postgresql/data

    volumes:
      db_data:
  YAML
}

# ------------------------------------------------------------------
# Index file
# ------------------------------------------------------------------
resource "local_file" "index" {
  filename        = "${local.out}/INDEX.txt"
  file_permission = "0644"
  content         = <<-TXT
    Full-Stack Local Sim — ${var.project_name}
    ============================================

    Ports
    -----
    API      : http://localhost:${random_integer.api_port.result}
    Worker   : (internal) port ${random_integer.worker_port.result}
    Frontend : http://localhost:${random_integer.frontend_port.result}

    Files
    -----
    ${local.out}/docker-compose.yml
    ${local.out}/.env.master
    ${local.out}/services/api/.env
    ${local.out}/services/worker/.env
    ${local.out}/services/frontend/.env

    Quick start
    -----------
    cd ${local.out}
    docker compose --env-file .env.master up -d
  TXT
}

# ------------------------------------------------------------------
# Print index after apply
# ------------------------------------------------------------------
resource "null_resource" "print_index" {
  triggers = {
    always = plantimestamp()
  }

  provisioner "local-exec" {
    command = "cat '${local_file.index.filename}'"
  }

  depends_on = [local_file.index]
}
